created the home page and the navbar component the routing work is no…
EshaanAgg/LFXMM-Frontend pull request #11
Opened 2023-10-05 12:10 UTC by Min2who

![Screenshot (64)](https://github.com/EshaanAgg/LFXMM-Frontend/assets/127925465/eccf5bcd-0fbf-4d96-9f3c-c9f892fb259e)
added the homepage and the navbar although the routing part is not added properly 
solves issues #2

2023-10-05 12:23 UTC, EshaanAgg requested changes
The UI looks good but needs some changes.

2023-10-05 12:23 UTC, EshaanAgg commented on src/layouts/Layout.astro
> +
Properly indent the code. Use Astro's VS Code extension to auto-format the code for constitency.

2023-10-06 07:26 UTC, Min2who commented on package.json
> +		"rehype-external-links": "^3.0.0",
dont we need rehype-external-links  for google fonts link in the layout.astro page

2023-10-06 07:31 UTC, Min2who commented
![Screenshot (65)](https://github.com/EshaanAgg/LFXMM-Frontend/assets/127925465/fae9af84-7271-47f0-b71c-2ac40958b119)
when i have made the changes that you have mention above it is showing this error when i remove all the changes that i have made the page still give this error. Please can you specify what error i am facing

2023-10-07 16:37 UTC, EshaanAgg commented
Your branch has some conflicts. Push the latest code for the frontend and backend repos, and then try to make the changes. If the error persists, please give a more descriptive description of where the error is. This screen is too general to debug the error.

2023-10-28 05:30 UTC, Min2who commented
bhaiya the error is still there
what should i do

2023-10-28 07:58 UTC, EshaanAgg commented
@Min2who Your branch is way behind the current progress. Please pull the latest changes for the frontend as well as the backend, install the dependencies again, and then try. It should fix most of your issues.

2026-06-11 10:45 UTC, closed without merging