Org details page
EshaanAgg/LFXMM-Frontend pull request #12
Opened 2023-10-05 14:50 UTC by EsEmm04

created a organisation details page for each organisation and mapped data from API  and also attached some of the screenshots of the same.

<img width="911" alt="Screenshot 2023-10-05 201830" src="https://github.com/EshaanAgg/LFXMM-Frontend/assets/127090635/ac7cd5d5-34eb-42ff-895d-84ebf5577c02">

<img width="937" alt="Screenshot 2023-10-05 201931" src="https://github.com/EshaanAgg/LFXMM-Frontend/assets/127090635/a307db83-c450-4244-aa50-6cd81b86bf09">

2023-10-05 15:44 UTC, EshaanAgg requested changes
Good attempt, but there are some concerns which I have raised below. Please address them. Great work though!

2023-10-05 15:44 UTC, EshaanAgg commented on .env.sample
Do not delete this file.

2023-10-05 15:44 UTC, EshaanAgg commented on src/css/card.css
A couple of things about CSS. 
- We are using Tailwind as the CSS framework for this project. Do you wish to write this in tailwind or leave it as plain old CSS? Both work, but the choice is yours. 

If you wish to continue using it as CSS, make the following changes:
- Properly indent the CSS code. 
- Instead of using color values directly, define them in tailwind config and then use them.
- Instead of creating separate files, you can use scope CSS directly in Astro components. Look into the same.

2023-10-05 15:44 UTC, EshaanAgg commented on src/css/organisation.css
Same as the other CSS file.

2023-10-05 15:44 UTC, EshaanAgg commented on src/pages/cards.astro
Use titleCase names for class. Like `lowerSection` and not `lowersection`

2023-10-05 15:44 UTC, EshaanAgg commented on src/pages/cards.astro
> +            {description.substring(0,150)+'...'}
Add the handling for the case if the length of the description is less than 150. Then the `...` should not be displayed.

2023-10-05 15:44 UTC, EshaanAgg commented on src/pages/cards.astro
> +              Fall {programYear}
Replace `Fall` with `programTerm`.

2023-10-05 15:44 UTC, EshaanAgg commented on src/css/organisation.css
Is this card the same as `PastProjectCard` in #10? Please confirm.

2023-10-05 15:44 UTC, EshaanAgg commented on src/pages/organisation.astro
> +<div class="mainpage">
Rename the classes. 
And as I understand, this is currently just for providing a proof of concept of the styles right? The rendering for all the organizations would be something that you would work on later?

2023-10-05 16:53 UTC, EsEmm04 commented on src/css/organisation.css
yes bhaiya the card is same

2023-10-05 16:54 UTC, EsEmm04 commented on src/pages/organisation.astro
> +<div class="mainpage">
yes bhaiya

2023-10-05 19:11 UTC, EshaanAgg commented
I have just merged #10, which has introduced the card component into the repository. Pull the changes from it and try to use it in your project.

2023-10-07 07:36 UTC, EsEmm04 commented on src/css/card.css
i have intended CSS properly but not getting what I need to do for using Scope CSS for components

2023-10-07 16:35 UTC, EshaanAgg commented on src/css/card.css
There is a `style` tag that can be used in Astro to scope the styles to a particular component. It is very easy and mostly just involves copying and pasting CSS code. Check it out once.

2023-10-07 16:35 UTC, EshaanAgg commented on src/css/organisation.css
Alright. Then use the card from #10.

2023-10-07 16:35 UTC, EshaanAgg commented on src/pages/organisation.astro
> +<div class="mainpage">
Okay

2023-10-09 03:57 UTC, closed without merging