[ADDED]About Page
EshaanAgg/LFXMM-Frontend pull request #31
Opened 2023-12-11 15:12 UTC by ApoorvDubey23

Added About Us page

2023-12-11 16:09 UTC, EshaanAgg requested changes
@ApoorvDubey23 
A couple of changes are needed 
- The find that you are using is not being used anywhere in the site and looks inconsistent. Please use the fonts and styling similar to what has been used elsewehere.
- Instead of creating a new About Us page, rename the team page to about us, and on the top of it add this static content.

2023-12-11 16:09 UTC, EshaanAgg commented on src/assets/images/AboutUs.jpg
Crop the trademark. Try to use a SVG or webp if possible.

2023-12-12 05:02 UTC, ApoorvDubey23 commented on src/assets/images/AboutUs.jpg
Sure will try to find an SVG file , as currently the jpg file I am using is having a white background which I removed using online software , will try to find one

2023-12-12 05:53 UTC, ApoorvDubey23 commented on src/assets/images/AboutUs.jpg
Please Review the changes

2023-12-12 08:17 UTC, ApoorvDubey23 commented on src/assets/images/AboutUs.jpg
Bhaiya , mene ek mistake krdi thi , mene pull ni liya tha iss krn bhut saari gadbad ho jati site m , ek naya pull request generate kr rha with updated changes and sahi wala
Sorry for the inconvinience caused

2023-12-12 08:19 UTC, closed without merging